version: '3'

networks:
  internal:
    driver: bridge

services:
  postgres:
    image: postgres
    networks:
      - internal
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
  mpmbackend:
    build:
      context: mpmbackend
      dockerfile: Dockerfile
    volumes:
      - ./mpmbackend/app:/app
    container_name: mpmbackend
    environment:
      MPMBACKEND_PORT: ${MPMBACKEND_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      FLASK_APP: main.py
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - ${MPMBACKEND_PORT}:${MPMBACKEND_PORT}
    # command: flask run --host=0.0.0.0 --port=80
    # command: flask run --host=0.0.0.0 --port=80
